/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rafsan
 */
public class selectionPage extends javax.swing.JFrame {

    /**
     * Creates new form selectionPage
     */
    public selectionPage() {
        this.setTitle("Hotel Bukshi");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        bookingBar = new javax.swing.JMenu();
        checkinMenu = new javax.swing.JMenuItem();
        roomChange = new javax.swing.JMenuItem();
        checkoutBar = new javax.swing.JMenu();
        checkoutMenu = new javax.swing.JMenuItem();
        addedit = new javax.swing.JMenu();
        addMember = new javax.swing.JMenuItem();
        editMember = new javax.swing.JMenuItem();
        getReport = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/Image/2019-06-04.jpg"))); // NOI18N

        bookingBar.setText("Booking");
        bookingBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingBarActionPerformed(evt);
            }
        });

        checkinMenu.setText("Check In");
        checkinMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinMenuActionPerformed(evt);
            }
        });
        bookingBar.add(checkinMenu);

        roomChange.setText("Change Room");
        roomChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomChangeActionPerformed(evt);
            }
        });
        bookingBar.add(roomChange);

        jMenuBar2.add(bookingBar);

        checkoutBar.setText("Check Out");
        checkoutBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBarActionPerformed(evt);
            }
        });

        checkoutMenu.setText("Cheking Out...");
        checkoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutMenuActionPerformed(evt);
            }
        });
        checkoutBar.add(checkoutMenu);

        jMenuBar2.add(checkoutBar);

        addedit.setText("Add/Edit");

        addMember.setText("Add Member");
        addMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberActionPerformed(evt);
            }
        });
        addedit.add(addMember);

        editMember.setText("Edit Member");
        editMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMemberActionPerformed(evt);
            }
        });
        addedit.add(editMember);

        jMenuBar2.add(addedit);

        getReport.setText("Report");

        jMenuItem1.setText("Get Report");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        getReport.add(jMenuItem1);

        jMenuBar2.add(getReport);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkinMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinMenuActionPerformed
        try {
            new admin_choice().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(selectionPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(selectionPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_checkinMenuActionPerformed

    private void checkoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutMenuActionPerformed
        try {
            new CheckOut().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(selectionPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(selectionPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_checkoutMenuActionPerformed

    private void checkoutBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBarActionPerformed
        
    }//GEN-LAST:event_checkoutBarActionPerformed

    private void bookingBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingBarActionPerformed

    }//GEN-LAST:event_bookingBarActionPerformed

    private void roomChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomChangeActionPerformed
        try {
            new roomChange().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(selectionPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(selectionPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_roomChangeActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new report().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void addMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberActionPerformed
        try {
            new addMember().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(selectionPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(selectionPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_addMemberActionPerformed

    private void editMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMemberActionPerformed
        try {
            new editMember().setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(selectionPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(selectionPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editMemberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectionPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addMember;
    private javax.swing.JMenu addedit;
    private javax.swing.JMenu bookingBar;
    private javax.swing.JMenuItem checkinMenu;
    private javax.swing.JMenu checkoutBar;
    private javax.swing.JMenuItem checkoutMenu;
    private javax.swing.JMenuItem editMember;
    private javax.swing.JButton exit;
    private javax.swing.JMenu getReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem roomChange;
    // End of variables declaration//GEN-END:variables
}
